on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  npm-install:
    runs-on: linux
    steps:
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install @jcansdale-test/npm-load@1.0.949
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
